/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PFacilitatorsRouteImport } from './routes/p/facilitators'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PFacilitatorsRoute = PFacilitatorsRouteImport.update({
  id: '/p/facilitators',
  path: '/p/facilitators',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/facilitators': typeof PFacilitatorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/facilitators': typeof PFacilitatorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/facilitators': typeof PFacilitatorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/facilitators'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/facilitators'
  id: '__root__' | '/' | '/p/facilitators'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PFacilitatorsRoute: typeof PFacilitatorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/facilitators': {
      id: '/p/facilitators'
      path: '/p/facilitators'
      fullPath: '/p/facilitators'
      preLoaderRoute: typeof PFacilitatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PFacilitatorsRoute: PFacilitatorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
